# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/docker/machine";
    fetch = {
      type = "git";
      url = "https://github.com/docker/machine";
      rev = "49dfaa70fdc869c65d9f6c50c355624356ab383b";
      sha256 = "11vkx3rq1abxh32hm63k5645r74863ypi9v8jqgd6v6adaf769jn";
    };
  }
  {
    goPackagePath = "github.com/libvirt/libvirt-go";
    fetch = {
      type = "git";
      url = "https://github.com/libvirt/libvirt-go";
      rev = "6917086f8d2c6f329e8400f94add2ddd86e5cb71";
      sha256 = "1c0c34vxmzf2wwiw158xw5ksl4zxi7gy6bx84dbnir7rz70sbx0r";
    };
  }
]
