# Generated by debian-patches.sh from debian-patches.txt
let
  prefix = "https://sources.debian.org/data/main//s/squishyball/0.1~svn19085-5//debian/patches";
in
[
  {
    url = "${prefix}/ncurses_internals";
    sha256 = "134l7wklyg6z3bgfkl2myp2v8adm8zr5an6h7xmfx21aa06gmxbn";
  }
]
