# This file is autogenerated from update.sh in the same directory.
{
  dev = {
    version = "34.0.1809.0";
    url = "http://commondatastorage.googleapis.com/chromium-browser-official/chromium-34.0.1809.0.tar.xz";
    sha256 = "0hyqqqq2hzbzk325pk9bc70lsh0al2nqf1mlahybp5vigy5jzy88";
  };
  beta = {
    version = "33.0.1750.46";
    url = "http://commondatastorage.googleapis.com/chromium-browser-official/chromium-33.0.1750.46.tar.xz";
    sha256 = "04n43c4vn8i7qhlybqb19c2c8kri8nc1wpa2l83vin4sqxkq519h";
  };
  stable = {
    version = "32.0.1700.102";
    url = "http://commondatastorage.googleapis.com/chromium-browser-official/chromium-32.0.1700.102.tar.xz";
    sha256 = "0jxwhd7cd60ivisrnzcglqqnmy99np1vvjqa27y42d852xjx84ys";
  };
  node = {
    version = "0.8.4";
    url = "https://s3.amazonaws.com/node-webkit/v0.8.4/node-webkit-src-v0.8.4.tar.gz";
    sha256 = "3a41f1b6adce709171d552bbd91e0bd5f02abbfe1f89afc3544385a03b64106a";
  };
}
