# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "0fhcis79d4l9k98gvz7l9hv8ippx0sbbz0y783ilc0n8lvim98k1";
    sha256bin64 = "10jbphp25jmji3liiln2n4w940liha82ax5qsrdls9qmpcb3jgkd";
    version = "70.0.3538.45";
  };
  dev = {
    sha256 = "0sgprxfjgf8xfxmf4rnjzmh29frqkigswxi5vjnhnyvrkk5dv3ra";
    sha256bin64 = "1pqcjipdpg6l1pmq64gh5a4675dj332f0g7p25vmhfmz4vh5vy5f";
    version = "71.0.3569.0";
  };
  stable = {
    sha256 = "0dcyzsb70ssx5hd2b25ab3ydpqh7crhxab9zzi5gn99ywxh1afg3";
    sha256bin64 = "0w56k7hmdi9knjaw67kdmyz0fdkjmk2ldh2n4l1c6szkr66vq30q";
    version = "69.0.3497.100";
  };
}
