# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1hj9vl42hflzsxkzl7kv67hxcdbjf3vy9xik53d9m37g5pyxjqh1";
    sha256bin64 = "1fb0zrzz8nmgszb6xwlll8z667q7r8x1y3z7lfyy2jykzvvf2jf2";
    version = "73.0.3683.67";
  };
  dev = {
    sha256 = "19fwzxnsd1parqghv4b2mif3cj1k1m5hzqnjsnglkgv6xnqny98g";
    sha256bin64 = "1aag76dgcnwga1q4jdgm3ziqvxs1qvrsyqfd7bbsi7axz6qi135v";
    version = "74.0.3724.8";
  };
  stable = {
    sha256 = "07xwmlvmzfga61nrimqmzl7s29jb4kc94nkzwwlb7sh6nr55a7jc";
    sha256bin64 = "1jdj2jp4jvzi5a24dm56ls5kx6xpiiv98yx4si9z19lm5srrji8j";
    version = "72.0.3626.121";
  };
}
