# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1jy1nggpnv074p2b7ih58sc07mcjp9w62s5b0dvjwsslf8inxp9g";
    sha256bin64 = "1b1p7n3hlx56fh1jslb6ncmfxqygpgcbrp8hmp7714g12nvy57lg";
    version = "72.0.3626.53";
  };
  dev = {
    sha256 = "1327bya68h60nqhjsjsksv3hya6y61cdqysm2kndmrwscss1m0dj";
    sha256bin64 = "1jwp9s8qgkw8nndl3wnmdawcbzp1g3mxcwivc76asisppvvm22zw";
    version = "73.0.3664.3";
  };
  stable = {
    sha256 = "0icxdg4fvz30jzq0xvl11zlwc9anb3lr9lb8sn1lqxr513isjmhw";
    sha256bin64 = "07kiqx5bpk54il0ynxl61bs5yscxb470q2bw3sx6cxjbhmnvbcn2";
    version = "71.0.3578.98";
  };
}
