{ stdenv, lib, fetchFromGitHub, fetchgit, python2, gn, ninja
, fontconfig, expat, icu58, libglvnd, libjpeg, libpng, libwebp, zlib
, mesa, libX11
, AppKit, ApplicationServices, OpenGL, fixDarwinDylibNames
, is_debug ? false
}:

let
  # skia-deps.nix is generated by: ./skia-make-deps.sh 'angle2|dng_sdk|piex|sfntly'
  depSrcs = import ./deps.nix { inherit fetchgit; };
  gnOld = gn.overrideAttrs (oldAttrs: rec {
    version = "20190403";
    src = fetchgit {
      url = "https://gn.googlesource.com/gn";
      rev = "64b846c96daeb3eaf08e26d8a84d8451c6cb712b";
      sha256 = "1v2kzsshhxn0ck6gd5w16gi2m3higwd9vkyylmsczxfxnw8skgpy";
    };
  });
in
stdenv.mkDerivation {
  pname = "skia";
  version = "unstable-2022-06-30";

  src = fetchgit {
    url = "https://skia.googlesource.com/skia.git";
    rev = "d9eeef0790b96953a58142c888b7947cb80858b9";
    hash = "sha256-4qTZnFgNEl3HmpARkF2kgvVu7xtMmHdwXZVTmt8TeCM=";
  };

  postPatch = ''
    patchShebangs --host gn/
  '';

  nativeBuildInputs = [ python2 gn ninja ]
    ++ lib.optionals stdenv.isDarwin [ fixDarwinDylibNames ];

  buildInputs = [
    fontconfig expat icu58 libglvnd libjpeg libpng libwebp zlib
  ] ++ (if stdenv.isDarwin then [
    AppKit ApplicationServices OpenGL
  ] else [
    mesa libX11
  ]);

  preConfigure = with depSrcs; ''
    mkdir -p third_party/externals
    ln -s ${angle2} third_party/externals/angle2
    ln -s ${dng_sdk} third_party/externals/dng_sdk
    ln -s ${piex} third_party/externals/piex
    ln -s ${sfntly} third_party/externals/sfntly
  '';

  gnArgs = [
    "is_debug=${if is_debug then "true" else "false"}"
    "is_official_build=${if (!is_debug) then "true" else "false"}"
  ] ++ lib.optionals (!stdenv.hostPlatform.isStatic) [
    "is_component_build=true"
  ];

  configurePhase = ''
    runHook preConfigure
    gn gen out/Release --args="$gnArgs" -v
    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    ninja -C out/Release skia
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out

    # Glob will match all subdirs.
    shopt -s globstar

    # All these paths are used in some way when building aseprite.
    cp -r --parents -t $out/ \
      include/codec \
      include/config \
      include/core \
      include/effects \
      include/gpu \
      include/private \
      include/utils \
      src/gpu/**/*.h \
      third_party/externals/angle2/include \
      third_party/skcms/**/*.h

  '' + (if stdenv.hostPlatform.isStatic then ''
    install -Dm555 out/Release/libskia.a $out/lib/libskia.a
  '' else ''
    install -Dm555 out/Release/libskia.so $out/lib/libskia${stdenv.hostPlatform.extensions.sharedLibrary}
  '') + ''

    runHook postInstall
  '';

  meta = with lib; {
    description = "Skia is a complete 2D graphic library for drawing Text, Geometries, and Images";
    homepage = "https://skia.org/";
    license = licenses.bsd3;
    maintainers = with maintainers; [ ];
    platforms = platforms.all;
  };
}
